project:
  type: website
  output-dir: docs

website:
  title: "RFS Data Editors"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "FAQs"
        href: faqs.qmd
      - text: "README Checklist"
        href: readme.qmd
      - text: "License"
        href: license.qmd

format:
  html:
    theme:
      - cosmo
    css: assets/css/styles.css
    toc: true
    email-obfuscation: javascript
